# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  

development:
  <<: *default
  username: <%= ENV["DB_USER"] %> 
  password: <%= ENV["APP_DATABASE_PASSWORD"] %> 
  port: <%= ENV["APP_PORT"] %>
  database: apphotel_development

test:
  <<: *default
  username: <%= ENV["DB_USER"] %> 
  password: <%= ENV["APP_DATABASE_PASSWORD"] %> 
  port: <%= ENV["APP_PORT"] %>
  database: apphotel_test


production:
  <<: *default
  database: apphotel_production
  username: apphotel
  password: <%= ENV["APPHOTEL_DATABASE_PASSWORD"] %>
